# Generated by Django 3.2.8 on 2021-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='career-studio/home/testimonials/'),
        ),
    ]
