# Generated by Django 3.2.9 on 2021-11-26 15:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_newslettertext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-id'], 'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AddField(
            model_name='about',
            name='long_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
