# Generated by Django 3.2.8 on 2022-06-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_app', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='session',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
