# Generated by Django 3.2.9 on 2021-11-30 12:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('heading', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('subheading', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('educator_type', models.CharField(choices=[('high-school', 'High School'), ('postsecondary', 'Post Secondary')], default='"high-school', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_educator_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_educator_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Educators',
                'verbose_name_plural': 'Educators',
                'ordering': ['-id'],
            },
        ),
    ]
