# Generated by Django 3.2.9 on 2021-11-30 13:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeLifeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career-studio/educators/college-life')),
                ('heading', models.CharField(default='School Administrators', max_length=255)),
                ('learn_more', models.CharField(default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_collegelifeitems_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_collegelifeitems_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'High School Tab Item(s)',
                'verbose_name_plural': 'High School Tab Item(s)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HighSchoolTabItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career-studio/educators/high-school')),
                ('heading', models.CharField(default='Surveys', max_length=255)),
                ('subheading', models.CharField(default='Assessments that Build Self-Knowledge', max_length=255)),
                ('align', models.CharField(choices=[('left', 'LEFT'), ('right', 'RIGHT')], default='left', max_length=10)),
                ('body', models.TextField(default='Students complete interactive personality, interests and learning style assessments to help them better understand their unique strengths and interests.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_highschooltabitems_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_highschooltabitems_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'High School Tab Item(s)',
                'verbose_name_plural': 'High School Tab Item(s)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('heading', models.CharField(blank=True, default='Prepare Students for a Successful Future', max_length=255, null=True)),
                ('subheading', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('college_heading', models.CharField(blank=True, default='Create a College, Career and Life Readiness Culture', max_length=255, null=True)),
                ('college_subheading', models.TextField(blank=True, default='', null=True)),
                ('college_life_items', models.ManyToManyField(blank=True, related_name='college_life', to='educator_app.CollegeLifeItems')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_highschool_created', to=settings.AUTH_USER_MODEL)),
                ('high_school_tab_items', models.ManyToManyField(blank=True, related_name='high_school_tab', to='educator_app.HighSchoolTabItems')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_highschool_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'High School',
                'verbose_name_plural': 'High School',
                'ordering': ['-id'],
            },
        ),
    ]
