# Generated by Django 3.2.9 on 2021-11-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educator_app', '0002_collegelifeitems_highschool_highschooltabitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegelifeitems',
            options={'ordering': ['-id'], 'verbose_name': 'College Life Tab Item(s)', 'verbose_name_plural': 'College Life Tab Item(s)'},
        ),
    ]
