# Generated by Django 3.2.9 on 2021-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator_app', '0003_alter_collegelifeitems_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelifeitems',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='highschooltabitems',
            name='body',
            field=models.TextField(default='Students complete interactive personality, interests and learning style assessments to help them better understand their unique strengths and interests.'),
        ),
    ]
