# Generated by Django 3.2.9 on 2021-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator_app', '0004_auto_20211130_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='college_life_items',
            field=models.ManyToManyField(default='', related_name='college_life', to='educator_app.CollegeLifeItems'),
        ),
    ]
