# Generated by Django 3.2.9 on 2021-11-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator_app', '0005_alter_highschool_college_life_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegelifeitems',
            name='learn_more',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='college_life_items',
            field=models.ManyToManyField(blank=True, related_name='college_life', to='educator_app.CollegeLifeItems'),
        ),
    ]
