# Generated by Django 3.2.8 on 2021-12-06 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educator_app', '0006_auto_20211130_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSecondaryTabImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('align', models.CharField(choices=[('left', 'LEFT'), ('right', 'RIGHT')], default='left', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='educator',
            name='educator_type',
            field=models.CharField(choices=[('high-school', 'High School'), ('post-secondary', 'Post Secondary')], default='"high-school', max_length=255),
        ),
        migrations.CreateModel(
            name='PostSecondaryTabItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('heading', models.CharField(default='Surveys', max_length=255)),
                ('subheading', models.CharField(default='Assessments that Build Self-Knowledge', max_length=255)),
                ('align', models.CharField(choices=[('left', 'LEFT'), ('right', 'RIGHT')], default='left', max_length=10)),
                ('body', models.TextField(default='Body Text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_postsecondarytabitems_created', to=settings.AUTH_USER_MODEL)),
                ('image', models.ManyToManyField(blank=True, to='educator_app.PostSecondaryTabImages')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_postsecondarytabitems_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('heading', models.CharField(blank=True, default='Unite your Campus Around Student Success', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_postsecondary_created', to=settings.AUTH_USER_MODEL)),
                ('secondary_tab_items', models.ManyToManyField(blank=True, related_name='secondary_tab', to='educator_app.PostSecondaryTabItems')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_app_postsecondary_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
