# Generated by Django 3.2.8 on 2021-11-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_ourskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurSkill',
        ),
    ]
