# Generated by Django 3.2.8 on 2021-12-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_delete_ourskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='privacypolicy',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='termsandcondition',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='termsandcondition',
            name='created_at',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
