# Generated by Django 3.2.8 on 2021-12-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_auto_20211206_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_options', models.CharField(blank=True, choices=[('artistic', 'artistic'), ('social', 'social'), ('enterprising', 'enterprising'), ('investigative', 'investigative'), ('conventional', 'conventional'), ('realistic', 'realistic')], max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='career_library')),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('graph', models.CharField(blank=True, max_length=100, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
