# Generated by Django 3.2.8 on 2021-12-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0007_auto_20211221_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerlibrary',
            name='job_category',
            field=models.CharField(blank=True, choices=[('high', 1), ('mid', 2), ('low', 3)], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='careerlibrary',
            name='career_options',
            field=models.CharField(blank=True, choices=[('extravert', 'extravert'), ('adventurous', 'adventurous'), ('agreeable', 'agreeable'), ('neurotic', 'neurotic'), ('conscientious', 'conscientious')], max_length=100, null=True),
        ),
    ]
