# Generated by Django 3.2.8 on 2022-01-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_auto_20220103_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerlibrary',
            name='category',
            field=models.CharField(blank=True, choices=[('extravert', 'extravert'), ('adventurous', 'adventurous'), ('agreeable', 'agreeable'), ('neurotic', 'neurotic'), ('conscientious', 'conscientious')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careerlibrary',
            name='job_type',
            field=models.CharField(blank=True, choices=[('high', 1), ('mid', 2), ('low', 3)], max_length=100, null=True),
        ),
    ]
