# Generated by Django 3.2.8 on 2022-02-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0012_auto_20220120_1107'),
        ('cms_app', '0010_auto_20220105_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerlibraryuser',
            name='career_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality_test.jobmaster'),
        ),
    ]
