# Generated by Django 3.2.8 on 2022-02-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0012_selectcareer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.CharField(blank=True, max_length=512, null=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_app.selectcareer')),
            ],
        ),
    ]
