# Generated by Django 3.2.8 on 2022-02-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0015_recommendationnot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerLibraryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('alternative_title', models.CharField(blank=True, max_length=256, null=True)),
                ('low_salary', models.CharField(blank=True, max_length=128, null=True)),
                ('mid_salary', models.CharField(blank=True, max_length=128, null=True)),
                ('high_salary', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tasks', models.TextField(blank=True, null=True)),
                ('soft_skill', models.TextField(blank=True, null=True)),
                ('hard_skill', models.TextField(blank=True, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard', models.CharField(blank=True, max_length=256, null=True)),
                ('physical_activity', models.CharField(blank=True, max_length=128, null=True)),
                ('decision_making', models.CharField(blank=True, max_length=128, null=True)),
                ('repetitive', models.CharField(blank=True, max_length=128, null=True)),
                ('competitive', models.CharField(blank=True, max_length=128, null=True)),
                ('time_pressure', models.CharField(blank=True, max_length=128, null=True)),
                ('job_zone', models.CharField(blank=True, max_length=128, null=True)),
                ('majors', models.CharField(blank=True, max_length=256, null=True)),
                ('education_data', models.CharField(blank=True, max_length=256, null=True)),
                ('typical_industries', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
