# Generated by Django 3.2.8 on 2022-02-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0016_careerlibrarydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='career_profile/soft_skill')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='career_profile/soft_skill')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
