# Generated by Django 3.2.8 on 2022-03-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0017_hardskills_softskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkValueItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('achievement', 'achievement'), ('independence', 'independence'), ('recognition', 'recognition'), ('relationships', 'relationships'), ('support', 'support'), ('working conditions', 'working conditions')], max_length=128, null=True)),
                ('items', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkValuesScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('achievement', 'achievement'), ('independence', 'independence'), ('recognition', 'recognition'), ('relationships', 'relationships'), ('support', 'support'), ('working conditions', 'working conditions')], max_length=128, null=True)),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
