# Generated by Django 3.2.8 on 2022-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0020_userworkvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='workvalueitems',
            name='item_no',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
