# Generated by Django 3.2.8 on 2022-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0021_workvalueitems_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='workvalueitems',
            name='item_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workvalueitems',
            name='multiply_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
