# Generated by Django 3.2.8 on 2022-04-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0027_userselectedcareer'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='in_demand',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='sample_lectures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='typical_careers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='typical_subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
