# Generated by Django 3.2.8 on 2022-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0030_auto_20220728_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerlibrarydetail',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
