# Generated by Django 3.2.8 on 2021-12-16 08:15

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conscientious',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='personalitytest',
            name='personality_test',
            field=models.ManyToManyField(blank=True, to='personality_test.PersonalityAnswerModel'),
        ),
    ]
