# Generated by Django 3.2.8 on 2021-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0002_auto_20211216_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conscientious',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conscientious',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
