# Generated by Django 3.2.8 on 2021-12-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0002_auto_20211216_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityanswermodel',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityquestion',
            name='key_type',
            field=models.CharField(blank=True, choices=[('positive', 'positive'), ('negative', 'negative')], max_length=100, null=True),
        ),
    ]
