# Generated by Django 3.2.8 on 2021-12-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0003_auto_20211217_1042'),
        ('personality_test', '0003_auto_20211222_0455'),
    ]

    operations = [
    ]
