# Generated by Django 3.2.8 on 2021-12-23 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personality_test', '0004_merge_0003_auto_20211217_1042_0003_auto_20211222_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('age_group', models.CharField(blank=True, choices=[('13-19', 1), ('20-24', 2), ('25-40', 3), ('41-100', 4)], max_length=100, null=True)),
                ('assesment_category', models.CharField(blank=True, choices=[('extravert', 'extravert'), ('adventurous', 'adventurous'), ('agreeable', 'agreeable'), ('neurotic', 'neurotic'), ('conscientious', 'conscientious')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssesmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('user_score', models.PositiveIntegerField(default=0)),
                ('extravert', models.CharField(blank=True, max_length=100, null=True)),
                ('adventurous', models.CharField(blank=True, max_length=100, null=True)),
                ('agreeable', models.CharField(blank=True, max_length=100, null=True)),
                ('neurotic', models.CharField(blank=True, max_length=100, null=True)),
                ('assesment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality_test.personalitytest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personality_test_userassesmentstats_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personality_test_userassesmentstats_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
