# Generated by Django 3.2.8 on 2021-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0005_assessmentstats_userassesmentstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('category', models.CharField(choices=[('extravert', 'extravert'), ('adventurous', 'adventurous'), ('agreeable', 'agreeable'), ('neurotic', 'neurotic'), ('conscientious', 'conscientious')], max_length=100)),
                ('job_category', models.CharField(choices=[(1, 'high'), (2, 'mid'), (3, 'low')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assessmentstats',
            name='age_group',
            field=models.CharField(blank=True, choices=[('13-19', '13-19'), ('20-24', '20-24'), ('25-40', '25-40'), ('41-100', '41-100')], max_length=100, null=True),
        ),
    ]
