# Generated by Django 3.2.8 on 2021-12-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0006_auto_20211224_0700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conscientious',
            new_name='UserDetail',
        ),
        migrations.RenameField(
            model_name='personalitytest',
            old_name='conscientious',
            new_name='user_detail',
        ),
        migrations.AddField(
            model_name='userassesmentstats',
            name='conscientious',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobmaster',
            name='job_category',
            field=models.CharField(choices=[('high', 1), ('mid', 2), ('low', 3)], max_length=100),
        ),
    ]
