# Generated by Django 3.2.8 on 2022-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0007_auto_20211228_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassesmentstats',
            old_name='user_score',
            new_name='adventurous_score',
        ),
        migrations.AddField(
            model_name='userassesmentstats',
            name='agreeable_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userassesmentstats',
            name='conscientious_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userassesmentstats',
            name='extravert_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userassesmentstats',
            name='neurotic_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
