# Generated by Django 3.2.8 on 2022-01-07 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personality_test', '0008_auto_20220107_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('extravert_scale', models.CharField(blank=True, max_length=128, null=True)),
                ('adventurous_scale', models.CharField(blank=True, max_length=128, null=True)),
                ('agreeable_scale', models.CharField(blank=True, max_length=128, null=True)),
                ('neurotic_scale', models.CharField(blank=True, max_length=128, null=True)),
                ('conscientious_scale', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personality_test_personalitydashboard_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personality_test_personalitydashboard_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
