# Generated by Django 3.2.8 on 2022-01-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0009_personalitydashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitydashboard',
            name='adventurous_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalitydashboard',
            name='agreeable_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalitydashboard',
            name='conscientious_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalitydashboard',
            name='extravert_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalitydashboard',
            name='neurotic_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
