# Generated by Django 3.2.8 on 2022-01-10 08:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0010_auto_20220110_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityReportMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('extravert', 'extravert'), ('adventurous', 'adventurous'), ('agreeable', 'agreeable'), ('neurotic', 'neurotic'), ('conscientious', 'conscientious')], max_length=128)),
                ('category_description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('category_detail', models.TextField(default='')),
                ('score', models.CharField(choices=[('high', 1), ('mid', 2), ('low', 3)], max_length=128)),
                ('score_description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('strength', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('weakness', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
    ]
