# Generated by Django 3.2.8 on 2021-12-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestdetail',
            old_name='text_timing',
            new_name='duration',
        ),
    ]
