# Generated by Django 3.2.8 on 2021-12-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0002_rename_text_timing_interestdetail_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestquestion',
            options={'ordering': ['question_no']},
        ),
    ]
