# Generated by Django 3.2.8 on 2021-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0004_alter_answermodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer',
            field=models.CharField(help_text='like(1) to dislike(5)', max_length=10),
        ),
    ]
