# Generated by Django 3.2.8 on 2021-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0006_auto_20211208_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteresttest',
            name='answer',
            field=models.ManyToManyField(blank=True, to='interest_app.AnswerModel'),
        ),
    ]
