# Generated by Django 3.2.8 on 2021-12-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0007_alter_userinteresttest_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteresttest',
            name='exam_status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Complete', 'Complete')], default='InProgress', max_length=30),
        ),
    ]
