# Generated by Django 3.2.8 on 2022-01-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0008_userinteresttest_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestquestion',
            name='question_category',
            field=models.CharField(choices=[('artistic', 'artistic'), ('conventional', 'conventional'), ('social', 'social'), ('realistic', 'realistic'), ('investigative', 'investigative'), ('enterprising', 'enterprising')], default='', max_length=128),
        ),
    ]
