# Generated by Django 3.2.8 on 2022-01-11 09:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interest_app', '0009_interestquestion_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestReportMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.CharField(choices=[('creator', 'creator'), ('organizer', 'organizer'), ('helper', 'helper'), ('doer', 'doer'), ('thinker', 'thinker'), ('persuader', 'persuader')], default='', max_length=128)),
                ('category_description', models.TextField(default='')),
                ('category_are', models.TextField(default='')),
                ('category_like', models.TextField(default='')),
                ('category_value', models.TextField(default='')),
                ('category_makes', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('category_work', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('artistic_score', models.FloatField(default=0)),
                ('conventional_score', models.FloatField(default=0)),
                ('social_score', models.FloatField(default=0)),
                ('realistic_score', models.FloatField(default=0)),
                ('enterprising_score', models.FloatField(default=0)),
                ('investigative_score', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_app_userscores_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_app_userscores_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
