# Generated by Django 3.2.8 on 2022-01-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_guestuser'),
        ('interest_app', '0010_interestreportmaster_userscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.guestuser'),
        ),
        migrations.AddField(
            model_name='userinteresttest',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.guestuser'),
        ),
        migrations.AddField(
            model_name='userscores',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.guestuser'),
        ),
    ]
