# Generated by Django 3.2.8 on 2022-02-04 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_guestuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interest_app', '0011_auto_20220119_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestAnswerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('answer', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('exam_status', models.CharField(choices=[('InProgress', 'InProgress'), ('Complete', 'Complete')], default='InProgress', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_app_interestanswerdata_created', to=settings.AUTH_USER_MODEL)),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.guestuser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_app_interestanswerdata_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
