# Generated by Django 3.2.8 on 2021-12-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
