# Generated by Django 3.2.8 on 2021-12-10 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('answer', models.CharField(help_text='like(1) to dislike(5)', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_style_learninganswermodel_created', to=settings.AUTH_USER_MODEL)),
                ('question_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_style.learningquestion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_style_learninganswermodel_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningUserInterestTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('exam_status', models.CharField(choices=[('InProgress', 'InProgress'), ('Complete', 'Complete')], default='InProgress', max_length=30)),
                ('answer', models.ManyToManyField(blank=True, to='learning_style.LearningAnswerModel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_style_learninguserinteresttest_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_style_learninguserinteresttest_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userinteresttest',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='userinteresttest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userinteresttest',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AnswerModel',
        ),
        migrations.DeleteModel(
            name='UserInterestTest',
        ),
    ]
