# Generated by Django 3.2.8 on 2021-10-22 10:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_alternativetitles_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_alternativetitles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alternative Title',
                'verbose_name_plural': 'Alternative Titles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('profile_type', models.CharField(choices=[('Artistic', 'Artistic'), ('Social', 'Social'), ('Enterprising', 'Enterprising'), ('Investigative', 'Investigative'), ('Conventional', 'Conventional'), ('Realistic', 'Realistic')], default='Artistic', max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('banner_type', models.CharField(choices=[('Video', 'Video'), ('Image', 'Image')], default='Video', max_length=10)),
                ('banner_url', models.CharField(max_length=255)),
                ('profile_description', ckeditor.fields.RichTextField()),
                ('profile_image', models.ImageField(upload_to='career-profile/images/')),
                ('career_detail', ckeditor.fields.RichTextField()),
                ('alternative_title', models.ManyToManyField(to='career.AlternativeTitles')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careerprofile_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Profile',
                'verbose_name_plural': 'Career Profiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('skill_type', models.CharField(choices=[('soft', 'Soft'), ('hard', 'Hard')], default='hard', max_length=5)),
                ('skill_name', models.CharField(max_length=65)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_skill_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_skill_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('country_name', models.CharField(max_length=50)),
                ('country_code', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_country_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_country_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='CareerProfileGlance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('title', models.CharField(max_length=70)),
                ('rating', models.CharField(max_length=15)),
                ('career_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.careerprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careerprofileglance_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careerprofileglance_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Profile Glance',
                'verbose_name_plural': 'Career Profile Glance',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='hard_skill',
            field=models.ManyToManyField(related_name='hard_skill', to='career.Skill'),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='soft_skill',
            field=models.ManyToManyField(related_name='soft_skill', to='career.Skill'),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careerprofile_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AverageSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('avg_sal_entry', models.CharField(max_length=50)),
                ('avg_sal_mid', models.CharField(max_length=50)),
                ('avg_sal_senior', models.CharField(max_length=50)),
                ('career_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.careerprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_averagesalary_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.country')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_averagesalary_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Average Salary',
                'verbose_name_plural': 'Average Salaries',
                'ordering': ['-id'],
            },
        ),
    ]
