# Generated by Django 3.2.8 on 2021-10-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='career-profile/images/'),
        ),
    ]
