# Generated by Django 3.2.8 on 2021-10-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_careerprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerprofileglance',
            name='rating',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=15),
        ),
    ]
