# Generated by Django 3.2.8 on 2021-10-25 06:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0003_alter_careerprofileglance_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCommonIndustries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('description', ckeditor.fields.RichTextField()),
                ('private', models.BooleanField(default=False)),
                ('government', models.BooleanField(default=False)),
                ('career_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.careerprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careercommonindustries_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careercommonindustries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Common Industry',
                'verbose_name_plural': 'Career Common Industries',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CareerEducationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('description', ckeditor.fields.RichTextField()),
                ('bachelor_degree', models.BooleanField(default=False)),
                ('master_degree', models.BooleanField(default=False)),
                ('college', models.CharField(max_length=255)),
                ('specialisation', models.CharField(max_length=255)),
                ('career_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.careerprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careereducationrequirement_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careereducationrequirement_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Education Requirement',
                'verbose_name_plural': 'Career Education Requirements',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CareerCommonIndustriesBreakup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('type', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government')], default='Private', max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('percentage', models.CharField(max_length=50)),
                ('common_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.careercommonindustries')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careercommonindustriesbreakup_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_careercommonindustriesbreakup_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Common Industries Breakup',
                'verbose_name_plural': 'Career Common Industries Breakup',
                'ordering': ['-id'],
            },
        ),
    ]
