# Generated by Django 3.2.8 on 2021-10-27 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0005_auto_20211026_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('credit_hours', models.CharField(max_length=20)),
                ('annual_tution_fee_local', models.IntegerField()),
                ('annual_tution_fee_international', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_schoolmajor_created', to=settings.AUTH_USER_MODEL)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.majorsetup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.schoolprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_schoolmajor_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMajorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('sub_desc', models.TextField()),
                ('video_url', models.URLField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_schoolmajorsubject_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.schoolprofile')),
                ('school_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.schoolmajor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_schoolmajorsubject_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Major Subject',
                'verbose_name_plural': 'School Major Subjects',
                'ordering': ['-id'],
            },
        ),
    ]
