# Generated by Django 3.2.8 on 2022-04-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_auto_20211206_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='country_rank',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='world_rank',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
