# Generated by Django 3.2.9 on 2021-11-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourachievementitems',
            options={'ordering': ['-id'], 'verbose_name': 'Our Achievement Item(s)', 'verbose_name_plural': 'Our Achievement Item(s)'},
        ),
        migrations.AlterField(
            model_name='ourachievement',
            name='our_achivement_items',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='about_app.OurAchievementItems'),
        ),
    ]
