# Generated by Django 3.2.9 on 2021-11-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0003_auto_20211127_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourachievement',
            name='sprint',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
    ]
