# Generated by Django 3.2.9 on 2021-11-27 10:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about_app', '0005_alter_ourachievement_subheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='career-studio/about/team')),
                ('fb_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tw_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('insta_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('linked_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_app_ourteamitems_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_app_ourteamitems_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Our Team Item(s)',
                'verbose_name_plural': 'Our Team Item(s)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('heading', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('subheading', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_app_ourteam_created', to=settings.AUTH_USER_MODEL)),
                ('our_teams', models.ManyToManyField(blank=True, related_name='our_teams', to='about_app.OurTeamItems')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_app_ourteam_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Our Team',
                'verbose_name_plural': 'Our Team',
                'ordering': ['-id'],
            },
        ),
    ]
