# Generated by Django 3.2.8 on 2021-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0006_ourteam_ourteamitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourachievementitems',
            name='count',
            field=models.CharField(default='16+', max_length=15),
        ),
        migrations.AlterField(
            model_name='ourachievementitems',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='career-studio/about/achievement'),
        ),
        migrations.AlterField(
            model_name='ourachievementitems',
            name='text',
            field=models.CharField(default='Specialists', max_length=150),
        ),
        migrations.AlterField(
            model_name='ourteamitems',
            name='fb_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ourteamitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='career-studio/about/team'),
        ),
        migrations.AlterField(
            model_name='ourteamitems',
            name='insta_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ourteamitems',
            name='linked_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ourteamitems',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='ourteamitems',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ourteamitems',
            name='tw_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
