# Generated by Django 3.2.8 on 2021-12-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0007_auto_20211130_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourachievement',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='ourachievementitems',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='ourteam',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='ourteamitems',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='ourachievement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ourachievementitems',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ourteamitems',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ourachievement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ourachievementitems',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ourteamitems',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
